name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - uses: jetli/wasm-pack-action@v0.4.0
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn prettier:check
      - run: yarn lint

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: jetli/wasm-pack-action@v0.4.0
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
